apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
  metadata:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    repoURL: https://github.com/Rollson/nginx-dev.git
    targetRevision: HEAD # always the last commit in the git repo
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  #creates namespace (L14) if it does not exist

    automated:
      selfHeal: true
      prune: true
